### ISSUE TITLE
Does not detect external GPU on optimus laptop

### ISSUE THREAD

**Issue by Kirtai** [flathub/com.revolutionarygamesstudio.ThriveLauncher#40]
I have a laptop with both Intel graphics and an nvidia GTX1060 but the launcher will only run the game under the Intel gpu.

**Comment by hhyyrylainen** [comment]
Is this specifically a launcher, flatpak or issue elsewhere? Have you tried running Thrive by itself to see if it can use external GPU? Or is the issue specifically that this kind of GPU offload doesn't work through flatpak or through the specific settings for the Thrive Launcher flatpak?

**Comment by Kirtai** [comment]
Thrive ran alone defaults to the Intel GPU.
Thrive ran from the flatpak launcher defaults to the Intel GPU.
Thrive ran alone or from the launcher flatpak with the env vars
```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia
```
runs with the GTX1060.

So it seems that Thrive is not autodetecting it.

Some other flatpaks I use *do* detect it automatically so I'm not sure why not.

This is on EndeavourOS (arch derivative) with KDE Plasma 6 and Wayland.

**Comment by hhyyrylainen** [comment]
Thrive uses Godot engine 3.5 currently. The next release is updating to Godot 4. If Godot 4 doesn't currently automatically handle optimus laptops opening a feature suggestion to them would be good. Alternatively if it takes just a few environment variables to be set, this could also be a feature request for the [Thrive launcher](https://github.com/Revolutionary-Games/Thrive-Launcher/issues) to have a checkbox for setting those variables to the Thrive process before starting it.

I'll close this as this isn't a specifically problem with the flatpak environment.

**Comment by Kirtai** [comment]
Alright, I'll wait to see how Godot 4 handles things.
Thanks :)
